### ISSUE TITLE
2020-11-11 KRD and BBL meeting (experiment 1 results and paper)

### ISSUE THREAD

**Issue by kdorheim** [FoRTExperiment/forte-disturbance#1]
@bpbond tomorrow let's talk about https://rpubs.com/kdorheim/689846 and ideas about the paper 

See zip file for results discussed on 2020-11-12
[Experiment_1.nb.html.zip](https://github.com/FoRTExperiment/forte-disturbance/files/5549241/Experiment_1.nb.html.zip)

Next Steps
* Add met data plots
* Do a series of runs to test out different event/disturbance events right now we are concerned that the ABG was reduced by almost 95% for all the FoRTE treatments

**Comment by kdorheim** [comment]
@bpbond and I met briefly to discuss  [Disturbance_Treatments.nb.html.zip](https://github.com/FoRTExperiment/forte-disturbance/files/5549233/Disturbance_Treatments.nb.html.zip) which looked at results from various event/harvest XML configurations. 

We are confident that the model is responding as expected to the event file we are using. Now we need to determine what event is most girdling like. 

Next Steps 
- [x] shift the disturbance to pre leaf out (January!)
- [x] disrupt all of the above-ground biomass (leaving the below-ground biomass alone)


** one idea that was discussed was increasing the length of time for the C storage impact since girdling is permanent however we decided to leave this idea until after we've met to discuss the pre-leaf out and agb runs

**Comment by kdorheim** [comment]
@bpbond We've got results from the different January disturbance and the above-ground biomass disturbance see 
[Disturbance_Treatments.nb.html-2020_11_18.zip](https://github.com/FoRTExperiment/forte-disturbance/files/5561683/Disturbance_Treatments.nb.html-2020_11_18.zip)
 for all the results. The January harvest had no impact, where as disturbing the above-ground biomass (leaving only the below-ground biomass) had more of the impact we were looking for. 🤔

**Comment by bpbond** [comment]
Thanks for running these @kdorheim ! OK, that seems doable—we need to disturb the entire aboveground biomass, not just storage. Seems reasonable and defensible.

If you haven't already, I'd suggest sometime soon we create a google doc and start making notes about the methods. This can be slowly developed into the core of a manuscript down the road!

**Comment by kdorheim** [comment]
@bpbond Yes, I can set up a google doc. Do you think I should go ahead and launch the experiment 1 runs (the full 1900 - 2030) runs with the entire aboveground biomass pertubations?

**Comment by bpbond** [comment]
I think so? It's fairly easy to set up, but then just needs to run for a few days or whatever?

**Comment by kdorheim** [comment]
Yup! I am going to close this issue, launch the runs, and start the google doc.
